### ISSUE TITLE
Build interstitial experience for Surveillance snippet campaign

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#41]
#### RACI:

Driver: @edrushka
Dev: @ScottDowne and/or @alicoding 
Decision Maker: @valianttry (who will also act as liaison for MoCo signoffs)
#### Milestones:
- [ ] Build finalized: Wednesday April 29 EOD
- [ ] QA: Thursday April 30

Design ticket it here: https://github.com/MozillaFoundation/movement-building/issues/40

**Comment by ScottDowne** [comment]
My copy is probably outdated, I'm missing transitions, icons, the eye, and probably other small bits.

But, here is a slice through content, style, and just enough interaction to make it explorable: http://scottdowne.github.io/surveillance-interstitial/public/

**Comment by ScottDowne** [comment]
Forgot that the last step needs to be dynamic depending on the answers.
- [x] Make final CTA dynamic.

**Comment by edrushka** [comment]
@valianttry please send Scott final copy when it's ready!

**Comment by ScottDowne** [comment]
Copy is easy to swap out, so I don't mind working with whatever until closer to the end.

**Comment by cassiemc** [comment]
Here's the feedback from Moco via email. I am cutting svg assets this morning.
- [x] Love the education and the conditional “answers” given to users.
- [x] Love the eyeball!
- [ ] The site doesn’t explicitly call out that Mozilla is for “stopping mass surveillance.” Maybe this can be woven into the petition CTA.
- [ ] Right now the petition CTA is to “help make civil liberties an important part of the conversation,” but the petition itself is more aggressive than this. Want to be super clear to our users. Maybe we say something to the nature: “Mozilla has this stance. If you agree based on what you’ve learned, sign this petition to XXX.”
- [ ] There is exact repetitive language ending the response we give to people who click “No” on questions 2 and 3. Potential risk here in that users will have already seen that language and may not read the more important first sentence of Question 3 thinking it is the same thing as they just read. Suggest removing the last sentence of response to Question 3 or rewording it so that it is different than response 2.
- [x] The mock up doesn’t have language for responses to Question 1 “No” or Questions 2 or 3 “Yes” -- could we review? [cassie: the responses are not dependent on a Yes or No]
- [ ] There is a disconnect with the headline copy “If I’m not under investigation…” and the subsequent questions. (We see where you are taking this but it’s not intuitive.)
- [ ] I don’t think it’s clear enough in the copy that this is the current state of affairs, and I can change anything.
  - “The U.S. government currently monitors…”
  - “As it stands today, the Patriot Act provision…”
  - “Right now, the Patriot Act does allow for…

**Comment by cassiemc** [comment]
@ScottDowne The x's aren't working for me to reset the questions, not sure if you're there yet.

**Comment by cassiemc** [comment]
@ScottDowne All graphic assets are here: https://www.dropbox.com/sh/7ntv3psltharl73/AACmT0oRg_0t2dUiX5YD7ozLa?dl=0

**Comment by edrushka** [comment]
Here is the revised copy, which should address all the issues above: https://etherpad.mozilla.org/interstitial-copy

**Comment by cassiemc** [comment]
@ScottDowne Here is the design with the grid overlaid: https://www.dropbox.com/s/birsnwif0e0qyzx/surveillance-v4-complete-grid.png?dl=0 It's okay if things need to shift a little bit.

![surveillance-v4-complete-grid](https://cloud.githubusercontent.com/assets/1186326/7396782/fc0904f0-ee71-11e4-96c1-dc342b3eb014.png)

**Comment by edrushka** [comment]
Final copy for interstitial page is here: https://etherpad.mozilla.org/interstitial-copy

**Comment by edrushka** [comment]
MVPs before we ship this page:
- [x] add the 2nd CTA. Copy is:

Right now the U.S. Congress is rethinking mass surveillance. Learn about Mozilla's position on surveillance reforms needed to protect civil liberties. Learn more.
- [x] update the copy. See previous comment.
- [x] add the link in the upper left. [Details here.](https://github.com/MozillaFoundation/movement-building/issues/45)

**Comment by ScottDowne** [comment]
@edrushka Where does the 2nd cta link go?

**Comment by edrushka** [comment]
@ScottDowne https://blog.mozilla.org/netpolicy/2015/04/14/stop-mass-surveillance-under-the-patriot-act/

**Comment by davidascher** [comment]
`Learn More` probably shouldn't be both the last phrase in the last para as well as the copy of the button.

**Comment by valianttry** [comment]
@ScottDowne I am getting broken image links:
chrome: http://note.io/1JTWCMa 
FF: http://note.io/1HSrEoR 
the eye image is gone completely from Chrome
we may share this on social so should work in most browsers.

**Comment by ScottDowne** [comment]
Yeah, the BSD page is still just a placeholder.

http://scottdowne.github.io/surveillance-interstitial/public/

^^ Is still the main link and is expected to work in chrome, if not, I need to fix.

**Comment by flukeout** [comment]
@ScottDowne @cassiemc - here are some animations for the icons, let me know if you'd like any changes to these, the phone rings 3 times and stops. Please check in Firefox.

http://flukeout.com/examples/phone-anim/

**Comment by cassiemc** [comment]
These are beautiful @flukeout thank you!!! Will they work on mobile?

**Comment by flukeout** [comment]
@cassiemc Yeah they work - just verified in Firefox on Android.

**Comment by edrushka** [comment]
Nice, @flukeout These are super fun!

**Comment by flukeout** [comment]
Okay, cool - @ScottDowne What's the best way to get you this stuff?

**Comment by ScottDowne** [comment]
@flukeout I just pulled the styles, images, markup, and keyframes from your demo, it's live here: https://sendto.mozilla.org/page/content/surveillance-interstitial/

**Comment by ScottDowne** [comment]
Closing
