### ISSUE TITLE
QA interstitial experience for Surveillance snippet campaign

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/movement-building#42]
#### RACI:

Driver: @edrushka
Dev: @ScottDowne and/or @alicoding 
Informed: @simonwex 
#### Milestones:
- [x] Build finalized: Wednesday April 29 EOD
- [ ] QA: Thursday April 30
- [ ] Snippet dates: Friday May 1 to May 15 (to be confirmed, and dependent on conversion rates)
#### Individual tickets:

Design ticket: https://github.com/MozillaFoundation/movement-building/issues/40
Build ticket: https://github.com/MozillaFoundation/movement-building/issues/41

**Comment by cassiemc** [comment]
- [ ] Things in this screenshot are done

![surveillance - initial design qa](https://cloud.githubusercontent.com/assets/1186326/7418275/ac852dd6-ef3a-11e4-861e-0996dad9b6a2.png)

**Comment by cassiemc** [comment]
- [ ] Things in this screenshot are done

![surveillance - initial design bottom qa](https://cloud.githubusercontent.com/assets/1186326/7418319/059aa932-ef3b-11e4-8493-e76cb2fe3952.png)

**Comment by edrushka** [comment]
Minor issues identified in today's standup meeting:
- [x] Delete 1st sentence in CTA for petition (too long) -- Screenshot: http://note.io/1HZV5qN 
- [x] Can the auto-scroll send people to the very bottom after completing #3? Otherwise the sign button is still hidden.  -- Removing the sentence might fix this. Scott will explore other solutions if not. Could be a window size thing. We could also do some x-browser testing. HAve only done chrome and FF
- [x] Add an on-hover state on the "sign" button? - new hover state should be subtly darker.

**Comment by cassiemc** [comment]
A little bit more!
- [ ] Things in these screenshots are done

![surveillance-hover-square](https://cloud.githubusercontent.com/assets/1186326/7418493/4a0d8660-ef3c-11e4-8fbb-31c788b6cc30.png)

![surveillance-a little more](https://cloud.githubusercontent.com/assets/1186326/7418558/cb05ca02-ef3c-11e4-8a08-6d999ee6b61b.png)

**Comment by ScottDowne** [comment]
@cassiemc I love the above screenshot moment. You got the eye in mid blink and looks very creepy.

**Comment by cassiemc** [comment]
@ScottDowne haha indeed.

**Comment by ScottDowne** [comment]
@cassiemc I'm having a hard time finding actual pixel values for what you have in these screenshots. I'm also not sure if the image is in the correct scale for me to measure.

I can take a guess, but I'm not sure how specific you want it to be. My guess is going to be off by a few pixels, if that's ok I can do that.

**Comment by cassiemc** [comment]
@ScottDowne You don't have to be specific, my images were not meant to be. So that's fine!

@davidascher and I were just talking about the page scrolling speed, when it auto scrolls you. It should probably be a bit slower.

**Comment by cassiemc** [comment]
@ScottDowne Also thinking about the black and whiteness of the page when you first land. Can we try some color on the hover states for Yes / No? Fade to green for Yes, and Fade to red for No.

**Comment by cassiemc** [comment]
- [x] Let's get rid of the period after 'petition' in the link at the very top of the page. So, "sign the petition" not "sign the petion."
- [x] The quotes around "any tangible thing" should be smart quotes
- [x] The apostrophe in the headline should also be a smart quote if you can swing in
- [x] The numbers 2 and 3 are not quite centered in their circles (need to move to the right by 2-3px
- [x] All the numbers should be 'light' not bold or regular
- [x] The circles should be about 10% bigger (there should be a little bit more white space around the numbers)
- [x] The 'your answer' text should be white with an opacity of 40%. Otherwise, on green the text color is #8ac473, and on red the text color is #d79c9a
- [x] The box outlines around 'yes' and 'no' should also be white with an opacity of 40%

![surveillance alignment quotes](https://cloud.githubusercontent.com/assets/1186326/7423345/4a1e0910-ef62-11e4-8a3d-aabd4e3c4688.png)

**Comment by cassiemc** [comment]
Just wanted to make sure @davidascher's comment didn't get lost. I see this occasionally too – white text in the cta with no button background: https://www.dropbox.com/s/53nn0zl0tq2vcwn/Screenshot%202015-04-30%2014.03.50.png?dl=0

**Comment by ScottDowne** [comment]
I think what @davidascher is seeing is cache from the old page after I added the css to handle the hover.

Try clearing cache/private tab, should fix it.

**Comment by ScottDowne** [comment]
Did that checklist, slowed the scroll down a bit, and added the animated icons.

**Comment by ScottDowne** [comment]
Turns out the white button text with no blue background wasn't cache, it's a bug, should be fixed now.

**Comment by edrushka** [comment]
Fix orphans on the CTA:
CTA 1
Join Mozilla and tell Congress it's time 
to stop mass surveillance and 
protect civil liberties.

CTA 2
Learn about Mozilla's position on 
surveillance reforms needed to 
protect civil liberties.

**Comment by ScottDowne** [comment]
@cassiemc Think I got all the QA done.

One area that was a bit confusing was:

![surveillance-hover-square](https://cloud.githubusercontent.com/assets/1186326/7418493/4a0d8660-ef3c-11e4-8fbb-31c788b6cc30.png)

![surveillance-a little more](https://cloud.githubusercontent.com/assets/1186326/7418558/cb05ca02-ef3c-11e4-8a08-6d999ee6b61b.png)

If both of those are applied (not including the font changes), the no answer box is no longer lined up with the no question box.

Not sure I did this right, but if the initial box is smaller, and that box moves to create the final box, can I assume the final box should also be smaller? Example:

![size1](https://cloud.githubusercontent.com/assets/197334/7457893/d6fc1752-f25d-11e4-92f0-f4b8dfe0f5f8.png)

I kept the space between the "your answer" and the answer box the same as the screenshot (roughly 30px), while still making the box smaller, which in turn makes the no box move a bit to the left when clicked. Is this what you wanted?

You can see it all live here: http://scottdowne.github.io/surveillance-interstitial/public/

it's not shipped to prod yet, but I can if it is what you wanted (or better than what currently is on prod)

For comparison here is the prod link: https://sendto.mozilla.org/page/content/surveillance-interstitial/

**Comment by cassiemc** [comment]
@ScottDowne let's chat I'll ping you on IRC.

**Comment by ScottDowne** [comment]
@cassiemc works for me.

**Comment by cassiemc** [comment]
@ScottDowne I left some feedback on your mobile view on Redpen. https://redpen.io/sf070262186afaa61c

**Comment by ScottDowne** [comment]
Closing
